name: CI-build-test

run-name: "Workflow performing CI steps: build, unit testing, integration testing"

on:
  workflow_call:

env:
  RUST_BACKTRACE: 1

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-test-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-build-test-cargo-
      - name: Install deps
      # required by sc-network-sync
      # required by nh-runtime
      # required by nh-runtime
        run: |
            sudo apt-get install protobuf-compiler
            rustup target add wasm32-unknown-unknown
            rustup component add rust-src
      - name: Check
        run: cargo check --all-features --all-targets --release
      - name: Build
        run: cargo build --release
      - name: Unit tests
        run: |
          cargo test --lib --bins --all-features --no-fail-fast --release 2>&1 | tee unit_tests_output.txt
      - name: Integration tests
        run: |
          cargo test --test '*' --all-features --no-fail-fast --release 2>&1 | tee integration_tests_output.txt
      - name: Upload Unit Test Output
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-output
          path: unit_tests_output.txt
          if-no-files-found: warn
          retention-days: 1
          compression-level: 0
          overwrite: true

      - name: Upload Integration Test Output
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-output
          path: integration_tests_output.txt
          if-no-files-found: warn
          retention-days: 1
          compression-level: 0
          overwrite: true 
