name: Coverage

run-name: "Workflow CI/CD Steps: coverage"

on:
  workflow_call:

env:
  IMAGE_NAME: zencash/sc-ci-base
  IMAGE_TAG: noble_rust-stable_latest
  DOCKER_COMPOSE_CMD: "docker compose -f ${GITHUB_WORKSPACE}/ci/docker-compose.yml run --rm cargo-container"
  DOCKER_BUILD_DIR: /build
  DOCKER_CARGO_HOME: /tmp/.cargo
  CARGO_BINARIES_INSTALL: "cargo-llvm-cov"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Free up disk space
        run: ${GITHUB_WORKSPACE}/.github/scripts/clean_ci.sh

      - name: Set up cargo cache
        uses: actions/cache@v4
        if: ${{ !env.ACT }}
        continue-on-error: true
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: coverage-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: coverage-cargo-

      - name: Set docker env vars
        run: |
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "GRP_ID=$(id -g)" >> $GITHUB_ENV

      - name: Cargo coverage
        run: |
          ${{ env.DOCKER_COMPOSE_CMD }} sh -c '
            cargo llvm-cov clean --workspace \
            && find . -name "*.profraw" -delete \
            && cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info \
            && cargo llvm-cov report --json --output-path coverage_report.json --summary-only \
            && cargo llvm-cov report > coverage_summary.txt \
            && cat coverage_summary.txt \
          '

      - name: Upload output(s)
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-output
          path: coverage_report.json
          if-no-files-found: warn
          retention-days: 1
          compression-level: 0
          overwrite: true