name: CI-coverage

run-name: "Workflow performing CI step: coverage"

on:
  workflow_call:

env:
  RUST_BACKTRACE: 1

jobs:
  coverage:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Clean CI
        run: ./.github/scripts/clean_ci.sh
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-coverage-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-coverage-cargo-
      - name: Install deps
      # required by sc-network-sync
      # required by nh-runtime
      # required by nh-runtime
        run: |
            sudo apt-get install protobuf-compiler
            rustup target add wasm32-unknown-unknown
            rustup component add rust-src
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run cargo-tarpaulin for Coverage
        if: matrix.os == 'ubuntu-latest'
        env:
          RUSTFLAGS: -C debuginfo=2
        run: |
          cargo tarpaulin --engine=llvm --ignore-tests --skip-clean --release --implicit-test-threads 2>&1 | tee test_coverage_output.txt
      - name: Upload Test Coverage Output
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-output
          path: test_coverage_output.txt
          if-no-files-found: warn
          retention-days: 1
          compression-level: 0
          overwrite: true