name: CI-coverage

run-name: "Workflow performing CI step: coverage"

on:
  workflow_call:

env:
  RUST_BACKTRACE: 1

jobs:
  coverage:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Clean CI
        run: ./.github/scripts/clean_ci.sh
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-coverage-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-coverage-cargo-
      - name: Install deps
      # required by sc-network-sync
      # required by nh-runtime
      # required by nh-runtime
        run: |
            sudo apt-get install protobuf-compiler
            rustup target add wasm32-unknown-unknown
            rustup component add rust-src
      - name: Install coverage tools
        run: |
            cargo install --force cargo-llvm-cov
      - name: Coverage tasks
        run: |
            cargo llvm-cov clean --workspace
            find . -name "*.profraw" -delete
            cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
            cargo llvm-cov report --json --output-path coverage_report.json --summary-only
            cargo llvm-cov report > coverage-summary.txt
            cat coverage-summary.txt
      - name: Upload json summary as Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Upload coverage_report.json summary
          path: ./coverage_report.json
          if-no-files-found: warn
          retention-days: 1
          compression-level: 0
          overwrite: true
      # It is also possible to upload the generated lcov.info for later use with Codecov
      # (see https://llvm.org/docs/CommandGuide/llvm-profdata.html)
