name: CI-docker
run-name: "Workflow performing CI step: Docker Image Build and Publish"

on:
  workflow_call:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RELEASE_BRANCH: release

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build/Publish Docker image
        env:
          MAINTAINERS_KEYS: ${{ vars.MAINTAINERS_KEYS }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          if [ -n ${{ secrets.DOCKER_HUB_USERNAME }} ]; then echo "Secret var is not empty";else echo "Secret var is empty" && exit 1;fi
          source "${GITHUB_WORKSPACE}/ci/setup_env.sh"
          "${GITHUB_WORKSPACE}/ci/docker.sh"