name: Orchestrator

on:
  push:
    branches: [WEB3-588-Slack-Notifications]

jobs:
  build-test-job:
    uses: ./.github/workflows/CI-build-test.yml
  test-coverage-job:
    uses: ./.github/workflows/CI-coverage.yml
  lint-format-job:
    uses: ./.github/workflows/CI-lint-format.yml
  e2e-test-job:
    uses: ./.github/workflows/CI-e2e-test.yml

  notify-slack:
    runs-on: ubuntu-latest
    needs: [build-test-job,test-coverage-job,lint-format-job, e2e-test-job]
    steps:
      - name: Download Unit Test artifact
        uses: actions/download-artifact@v4
        with:
          name: unit-test-output
      - name: Download Integration Test artifact
        uses: actions/download-artifact@v4
        with:
          name: integration-test-output
      - name: Download Test Coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: test-coverage-output
      - name: Download formatting artifact
        uses: actions/download-artifact@v4
        with:
          name: formatting-output
      - name: Download linting artifact
        uses: actions/download-artifact@v4
        with:
          name: linting-output
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display unit test output
        run: cat unit-test-output.txt