name: Orchestrator

on:
  push:
    branches: [WEB3-588-Slack-Notifications]

jobs:
  build-test-job:
    uses: ./.github/workflows/CI-build-test.yml
  test-coverage-job:
    uses: ./.github/workflows/CI-coverage.yml
  lint-format-job:
    uses: ./.github/workflows/CI-lint-format.yml
  e2e-test-job:
    uses: ./.github/workflows/CI-e2e-test.yml

  notify-slack:
    runs-on: ubuntu-latest
    needs: [build-test-job,test-coverage-job,lint-format-job, e2e-test-job]
    if: ${{ always() }}
    steps:
      - name: Report Job Statuses
        run: |
          echo "Build and Test Job Status: ${{ needs.build-test-job.result }}"
          echo "Test Coverage Job Status: ${{ needs.test-coverage-job.result }}"
          echo "Lint and Format Job Status: ${{ needs.lint-format-job.result }}"
          echo "E2E Test Job Status: ${{ needs.e2e-test-job.result }}"
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display unit test output
        run: |
          if [ -f "unit_tests_output.txt" ]; then
            cat "unit_tests_output.txt"
          else
            echo "Unit test output not found."
          fi
      - name: Display integration test output
        run: |
          if [ -f "integration_tests_output.txt" ]; then
            cat "integration_tests_output.txt"
          else
            echo "Integration test output not found."
          fi
      - name: Display test coverage output
        run: |
          if [ -f "test_coverage_output.txt" ]; then
            cat "test_coverage_output.txt"
          else
            echo "Test Coverage output not found."
          fi
      - name: Display linting output
        run: |
          if [ -f "linting_output.txt" ]; then
            cat "linting_output.txt"
          else
            echo "Linting output not found."
          fi
      - name: Display formatting output
        run: |
          if [ -f "formatting_output.txt" ]; then
            cat "formatting_output.txt"
          else
            echo "Formatting output not found."
          fi