name: Rustdoc

run-name: "Workflow CI/CD Steps: rust doc generation"

on:
  workflow_dispatch:

env:
  IMAGE_NAME: zencash/sc-ci-base
  IMAGE_TAG: noble_rust-stable_latest
  DOCKER_COMPOSE_CMD: "docker compose -f ${GITHUB_WORKSPACE}/ci/docker-compose.yml run --rm cargo-container"
  DOCKER_BUILD_DIR: /build
  DOCKER_CARGO_HOME: /tmp/.cargo

jobs:
  rustdoc-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v4
        if: ${{ !env.ACT }}
        continue-on-error: true
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rustdoc-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set docker env vars
        run: |
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "GRP_ID=$(id -g)" >> $GITHUB_ENV

      - name: Generate Rust documentation
        run: ${{ env.DOCKER_COMPOSE_CMD }} cargo doc --no-deps --release

      - name: Redirect index.html
        run: |
          ${{ env.DOCKER_COMPOSE_CMD }} sh -c '
            echo "<meta http-equiv=\"refresh\" content=\"0; url=nh_node/index.html\">" > ${{ env.DOCKER_BUILD_DIR }}/target/doc/index.html
          '

      - name: Upload documentation
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  rustdoc-deployment:
    runs-on: ubuntu-latest
    needs: rustdoc-generation
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4