name: CI-tag-orchestrator

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]*'
  workflow_dispatch:

env:
  MAINTAINERS_KEYS: ${{ vars.MAINTAINERS_KEYS }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  YURI: ${{ secrets.YURI }}

jobs:
  docker-job:
    uses: ./.github/workflows/CI-docker.yml
  rustdoc-job:
    needs: docker-job
    uses: ./.github/workflows/CI-rustdoc.yml