name: CI-tag-orchestrator

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]*'
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest
    env:
      MAINTAINERS_KEYS: "value"  # Define your environment variables here
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Docker job
        uses: ./.github/workflows/CI-docker.yml  # Use the CI-docker workflow
  rustdoc-job:
    needs: docker-job
    uses: ./.github/workflows/CI-rustdoc.yml